### ISSUE TITLE
genList.remove(i) mal funcionamiento cuando i>(tamaño de la lista)

### ISSUE THREAD

**Issue by srjavimoure** [andreu-barro/VVS-DFA-JAVA#2]
Este método debería devolver un NullPointerException ya que la posición que le pasamos es mayor al tamaño de la lista.

Referencia al documento de prueba:
JAVA-GLIST-REM-01

**Comment by srjavimoure** [comment]
solucionado

**Comment by lauramcastro** [comment]
El cerrar una issue (salvo que se etiquete como `wontfix`) ya asume que se soluciona. Aprovechad el mensaje de cierre para enlazar con el commit correspondiente (usando el hash del mismo), y no dejéis de lado el uso de etiquetas y asignación de responsables.
