### ISSUE TITLE
Documentos de diseño de prueba por nivel, no por estrategia de pruebas

### ISSUE THREAD

**Issue by lauramcastro** [andreu-barro/VVS-DFA-JAVA#5]
En el enunciado de esta tercera semana se os pide un fichero diferente _por nivel de pruebas_, no por estrategia de pruebas. La estrategia usada (por ejemplo, mutación, análisis estático de caja blanca, valores frontera, etc.) es parte de la información que se os pedía la semana pasada en el campo "motivación" que debéis especificar para cada prueba.

**Comment by eoitaven** [comment]
Modificados los documentos para que estén por nivel de pruebas y no por estrategia
